version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bobbyahines/mouthrocks:prod
    container_name: app
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - '80:8080'
    volumes:
      - ./:/srv
    environment:
      - TZ=America/Los_Angeles
    command: npm run serve

networks:
  frontend:

